name: Install Topaz Photo AI

on:
  push:
    branches:
      - main

jobs:
  install_topaz:
    runs-on: windows-latest

    env:
      TOPAZ_VERSION: '2.2.2'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check if Folder Exists
      run: |
        if (-Not (Test-Path -Path $env:TOPAZ_VERSION)) {
          mkdir $env:TOPAZ_VERSION
        }

    - name: Download Topaz Photo AI MSI
      run: |
        Invoke-WebRequest -Uri "https://downloads.topazlabs.com/deploy/TopazPhotoAI/$env:TOPAZ_VERSION/TopazPhotoAI-$env:TOPAZ_VERSION.msi" -OutFile "$env:TOPAZ_VERSION\TopazPhotoAI-$env:TOPAZ_VERSION.msi"

    - name: Install Topaz Photo AI
      run: |
        Start-Process msiexec.exe -Wait -ArgumentList "/i $env:TOPAZ_VERSION\TopazPhotoAI-$env:TOPAZ_VERSION.msi /qn /l*v $env:TOPAZ_VERSION\logfile.txt"

    - name: Extract URLs
      run: |
        Get-Content $env:TOPAZ_VERSION\logfile.txt | Select-String -Pattern 'Setting up download from http://models.topazlabs.com/v1/' | ForEach-Object {
          $_.Matches.Value -replace 'http', 'https' } | Out-File -FilePath $env:TOPAZ_VERSION\models.txt

    - name: Generate README.md
      run: |
        # Read the template content if README.md exists, otherwise create a new one
        $templatePath = if (Test-Path "README.md") { "README.md" } else { "README_TEMPLATE.md" }
        $templateContent = Get-Content $templatePath -Raw
    
        # Replace placeholders with actual content
        $templateContent = $templateContent -replace 'TOPAZ_VERSION', $env:TOPAZ_VERSION
        $templateContent = $templateContent -replace 'BILIBILI_TUTORIAL_LINK', "https://www.bilibili.com/read/cv25993828"
        $templateContent = $templateContent -replace 'ARCHIVED_TUTORIAL_LINK', "https://archive.ph/HfQIm"
    
        # Add models table content without hash values
        $models = Get-Content $env:TOPAZ_VERSION\models.txt
        $modelsTableContent = $models | ForEach-Object { 
          $line = $_.ReadCount
          "| $line | $_ |`n" 
        }
        $templateContent = $templateContent -replace 'MODELS_TABLE_CONTENT', $modelsTableContent
    
        # Save the generated content to README.md
        $templateContent | Out-File -FilePath README.md
    
    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git add $env:TOPAZ_VERSION\models.txt
        git commit -m "Add latest models for Win"
        git push
