name: Install Topaz Photo AI

on:
  push:
    branches:
      - main

jobs:
  install_topaz:
    runs-on: windows-latest

    env:
      TOPAZ_VERSION: '2.2.2'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Topaz Photo AI MSI
        run: |
          Invoke-WebRequest -Uri "https://downloads.topazlabs.com/deploy/TopazPhotoAI/$env:TOPAZ_VERSION/TopazPhotoAI-$env:TOPAZ_VERSION.msi" -OutFile "TopazPhotoAI-$env:TOPAZ_VERSION.msi"

      - name: Install Topaz Photo AI
        run: |
          Start-Process msiexec.exe -Wait -ArgumentList "/i TopazPhotoAI-$env:TOPAZ_VERSION.msi /qn /l*v logfile.txt"

      - name: Extract URLs
        run: |
          Get-Content logfile.txt | Select-String -Pattern 'http://models.topazlabs.com/v1/' | ForEach-Object {
            $cleanedLink = $_ -replace '1: Log: \[1\] 2: Setting up download from http', 'https'
            $cleanedLink = $cleanedLink -replace '\s+$' # Remove trailing spaces
            $cleanedLink
          } | Out-File -FilePath models.txt

      - name: Run Python Script
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute Python Script
        run: |
          python main.py

      - name: Generate README.md
        run: |
          # Read the content from the final models file generated by main.py
          $modelsContent = Get-Content models.txt -Raw
      
          # Read the template content if README.md exists, otherwise create a new one
          $templatePath = if (Test-Path "README_TEMPLATE.md") { "README_TEMPLATE.md" } else { "README.md" }
          $templateContent = Get-Content $templatePath -Raw
      
          # Replace placeholders with actual content
          $templateContent = $templateContent -replace 'TOPAZ_VERSION', $env:TOPAZ_VERSION
          $templateContent = $templateContent -replace 'BILIBILI_TUTORIAL_LINK', "https://www.bilibili.com/read/cv25993828"
          $templateContent = $templateContent -replace 'ARCHIVED_TUTORIAL_LINK', "https://archive.ph/HfQIm"
      
          # Add models table content with auto-generated sequential numbering
          $lineNumber = 1
          $modelsTableContent = $modelsContent | ForEach-Object { 
            "| $lineNumber | $_ |`n"
            $lineNumber++
          }
      
          # Join the lines to form a single row in the table
          $modelsTableContent = $modelsTableContent -join ''
      
          $templateContent = $templateContent -replace 'MODELS_TABLE_CONTENT', $modelsTableContent
      
          # Save the generated content to README.md
          $templateContent | Out-File -FilePath README.md -Encoding utf8

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git add models.txt
          git commit -m "Add models-$env:TOPAZ_VERSION for Win"
          git push
